### ISSUE TITLE
Cookie command - Database

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#1]
/cookie to give a cookie to a user

Total cookies
Cookies in this server
Cookies given?

**Comment by RichardSabol** [comment]
I'd like to work on this. I found in repo, that cookie command is already implemented, database as well. Total cookies, cookies in this server and cookies given is just an extension of this functionality? Or what this issue consists of?

**Comment by KieranRobson** [comment]
> I'd like to work on this. I found in repo, that cookie command is already implemented, database as well. Total cookies, cookies in this server and cookies given is just an extension of this functionality? Or what this issue consists of?

I was working on this command but then life got in the way, if youd like to revamp the command or use whats already there, feel free!

My vision is to track the cookies received and cookies given by each member depending on the guild while also tracking the total cookies over multiple guilds. Feel free to run with this or change it up!

**Comment by RichardSabol** [comment]
Hi, I have a preview for you to adjust according to your desires. This is what I came with: 
![image](https://user-images.githubusercontent.com/63186863/195163062-0f6e13c8-c3a0-4355-b5a1-e3589e411395.png)

**Comment by RichardSabol** [comment]
I got your idea, but I just wanna for some more details about implementation. I came out with designs: 
![image](https://user-images.githubusercontent.com/63186863/195176586-5c72ba6a-bd62-459a-9390-438392acdd79.png) 
![image](https://user-images.githubusercontent.com/63186863/195176668-9681231d-8621-4028-9f88-a1af1aa3fc34.png)
Or my goal is just to prepare data without graphic output? Or how would you like to represent these data?

**Comment by KieranRobson** [comment]
I love the user info command! 

If the received cookies command could be moved from the footer itd be perfect!

Thats a reminder for the joined date 😆 I will be making an issue!
