### ISSUE TITLE
User Info command

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#2]
Pulls users into like date joined, roles, etc

**Comment by viktorluk311** [comment]
Hello, could you give me more details about this one? :)

**Comment by KieranRobson** [comment]
![image](https://user-images.githubusercontent.com/32241933/195854493-e16e5516-90bd-425b-8c65-f0e442c3c623.png)

This is the current layout of the userinfo command, just some more info about the user would be neat! 

See https://discord.js.org/#/docs/discord.js/main/class/User for more info

**Comment by viktorluk311** [comment]
Ok, you can assign it to me, i will try to work on it :)

**Comment by KieranRobson** [comment]
Go ahead @viktorluk311!
