### ISSUE TITLE
User info Joined Date Unknown 

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#23]
The user info date is showing as unknown, I tried a bunch to fix it. 

See below:
![image](https://user-images.githubusercontent.com/32241933/195182720-f6eb7385-e24c-4479-b829-a7f128898d20.png)

**Comment by rj564zi** [comment]
I am interested in your issue. Give me the opportunity to resolve it by assigning the issue.

**Comment by KieranRobson** [comment]
Thanks @rj564zi! Go ahead!

**Comment by rj564zi** [comment]
#76  its done

**Comment by rj564zi** [comment]
#82  function joinedAt is  working.

**Comment by rj564zi** [comment]
![image](https://user-images.githubusercontent.com/71985539/200203525-86da8380-b640-4c0d-bc6c-28e454d5d618.png)

**Comment by KieranRobson** [comment]
Implemented in #82
