### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#29]
In line with the community standard, issue templates could be added to make reporting issues easier

Heres a guide for if anyone would like to work on this! 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by code4Y** [comment]
I would like to work on this issue.

**Comment by KieranRobson** [comment]
Implemented in #65
