### ISSUE TITLE
Pull Request Templates 

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#30]
In line with the community standard, pull request templates could be added to make code validation easier and organisation better.

Heres a guide for if anyone would like to work on this!

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by KieranRobson** [comment]
Go ahead @Vinitvh!
