### ISSUE TITLE
Prints a random joke form the Joke API.

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#35]
I would like to add a command that prints a random joke form the Joke API. 

_Originally posted by @muditmahajan21 in https://github.com/KieranRobson/Clarence-Bot/issues/26#issuecomment-1277127402_

**Comment by muditmahajan21** [comment]
I would like to work on this

**Comment by KieranRobson** [comment]
To ahead @muditmahajan21!

**Comment by KieranRobson** [comment]
Implemented within #39
