### ISSUE TITLE
Command to send quotes using API

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#41]
_Originally posted by @darkbits018 in https://github.com/KieranRobson/Clarence-Bot/issues/26#issuecomment-1278573021_

**Comment by darkbits018** [comment]
Thank you Assign please

**Comment by KieranRobson** [comment]
Hi @darkbits018 

I was just wondering if you were still interested in completing this issue. No worries if not and ill unassign it!

**Comment by KieranRobson** [comment]
Implemented in #80
