### ISSUE TITLE
/trivia command that fetches a trivia type question

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#42]
Would like to add a /trivia command that fetches a trivia type question from [opentdb.com](https://opentdb.com/api.php?amount=1&type=boolean) API and lets the user interact with a &#9745; or &#9746;

_Originally posted by @muditmahajan21 in https://github.com/KieranRobson/Clarence-Bot/issues/26#issuecomment-1278589522_

**Comment by muditmahajan21** [comment]
Would like to develop this.
