### ISSUE TITLE
Error in /joke command 

### ISSUE THREAD

**Issue by muditmahajan21** [KieranRobson/Clarence-Bot#43]
Sometimes the bot would shut down after the /joke command.
Accidentally added the "n" alias for the -joke command
The description of /numberfact command is wrong.

Fix:
Add the deferReply to the /joke command to make it not throw an error if the interaction takes more than 3 seconds.
Remove the alias from the normal joke command
Edit the description of the /numberfact command

**Comment by KieranRobson** [comment]
Go ahead!
