### ISSUE TITLE
Minecraft data

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#6]
Ref: https://github.com/PrismarineJS/node-minecraft-data

When the user runs /Minecraftinfo 'block' an embed will appear with into about that block

**Comment by StanislavKysela** [comment]
Hi. I would like to work on this issue. Please give me an opportunity and assing it to me.

**Comment by StanislavKysela** [comment]
Thank you :)

**Comment by StanislavKysela** [comment]
Hello @KieranRobson. I made an embed with info about minecraft blocks. There is an example in the picture. Is it OK?
![image](https://user-images.githubusercontent.com/104487378/200090796-cb9ea6dc-0378-4787-b5b2-fc7c3c5fcafc.png)

**Comment by KieranRobson** [comment]
I love it!

**Comment by KieranRobson** [comment]
@StanislavKysela Feel free to open a pull request!

**Comment by StanislavKysela** [comment]
@KieranRobson I opened a pull request.

**Comment by KieranRobson** [comment]
Implemented in #81
