### ISSUE TITLE
/quote {string} for getting quotes from goodreads via scraping (axios)

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#69]
_Originally posted by @rk250ky in https://github.com/KieranRobson/Clarence-Bot/issues/26#issuecomment-1292288642_

**Comment by rk250ky** [comment]
can you assign me to this

**Comment by KieranRobson** [comment]
Go ahead @rk250ky!

**Comment by rk250ky** [comment]
Hello i got some problems with importing new libraries is there any special way to make new libraries connect to docker.
Getting error that i dont have module installed but it is in dependecies and node_modules.
