### ISSUE TITLE
Toggleable XP System

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#7]

**Comment by BranicekL** [comment]
Hello, I would like to work on this issue, if it's still available. Could you please assign it to me? Thanks.

**Comment by KieranRobson** [comment]
Go ahead @BranicekL

**Comment by BranicekL** [comment]
@KieranRobson Hello, I'm gonna work on this issue today. Could you please tell me more about this XP system, what should it do? I mean like should it add XP to user only for using bot commands of Clarence, or also for other server activity like joining voice calls, posting messages, etc.? Thank you. :)

**Comment by KieranRobson** [comment]
So when the user types a message, if you add extra stuff such as joining calls thatd be cool too!

I actually had an xp system working but removed it as it felt annoying when it wasn't toggleable: see [here](https://github.com/KieranRobson/Clarence-Bot/commit/7523b6adb5b9ed58090e1e5c0021d4e987e78269) for the xp system. The profile schema for this system can be found [here](https://github.com/KieranRobson/Clarence-Bot/blob/7523b6adb5b9ed58090e1e5c0021d4e987e78269/schemas/profile-schema.js)

 [here](https://github.com/KieranRobson/Clarence-Bot/commit/8d27a05604c141acfa193fbf85820e62e3af5da9) for the leaderboard that I created for it.

The leaderboard isnt required for this issue but its up to you if you want to implement it!
