### ISSUE TITLE
/Help Command

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#9]

**Comment by DuchVladimir** [comment]
Can you assign me this problem? I would like to help you with this or maybe also  with some other issues if you have already done this.

**Comment by KieranRobson** [comment]
@DuchVladimir Welcome! Go ahead!

**Comment by DuchVladimir** [comment]
I made pull request. I hope you like it. :)

**Comment by KieranRobson** [comment]
Implemented in #75
